version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: ${COMPOSE_PROJECT_NAME}-db
    ports:
      - "${HOST_PORT_MONGO}:27017"
    networks:
      - ve_network
    volumes:
      - mongo_data:/data/db

  # Pinned to a stable community version to bypass the new Auth Token requirement
  localstack:
    image: localstack/localstack:3.4.0
    container_name: ${COMPOSE_PROJECT_NAME}-aws
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - ve_network

networks:
  ve_network:
    driver: bridge

volumes:
  mongo_data: