services:
  app:
    build: 
      context: .
      # We will create the Dockerfile later, for now we prep the compose
    container_name: ${COMPOSE_PROJECT_NAME}-api
    ports:
      - "${HOST_PORT_BACKEND}:${PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - MONGO_URI=mongodb://mongo:27017/virtual_events
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - mongo
    networks:
      - ve_network
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules

  mongo:
    image: mongo:6.0
    container_name: ${COMPOSE_PROJECT_NAME}-db
    ports:
      - "${HOST_PORT_MONGO}:27017"
    networks:
      - ve_network
    volumes:
      - mongo_data:/data/db

networks:
  ve_network:
    driver: bridge

volumes:
  mongo_data: